test1:
	g++ main1.cpp -o main
	./main

test2:
	g++ main2.cpp -o main
	./main

test3:
	g++ main3.cpp -o main
	./main

test4:
	g++ main4.cpp -o main
	./main

test5:
	g++ main5.cpp -o main
	./main

test6:
	g++ main6.cpp -o main
	./main

test7:
	g++ main7.cpp -o main 
	./main

test8:
	g++ main8.cpp -o main
	./main
